config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'books#index'
  get 'books/assigntag'
  post 'assign_tags', to: 'books#assigntags'

  resources :authors
  resources :books
  resources :tags


  namespace :api do 
    namespace :v1 do
        get :books, to: 'books#index'
        get 'author_books', to: 'books#author_books'
        post 'createnewbook', to: 'books#createnewbook'
    end
  end

  


end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    has_many :bookstags
    has_many :tags, through: :bookstags, dependent: :destroy

    validates :title, length: { minimum: 5 }

end

app/controllers/api/v1/books_controller.rb
module Api
    module V1
        class BooksController < ApplicationController 
            
            def index
                books = Book.all
                render json: books, status: 200
            end
            def author_books
                author= Author.find_by_id(params[:id])
                books= author.books
                render json: books, except: :image
            end
            def createnewbook
                author= Author.find_by_id(params[:id])
                book = author.books.create(title: params[:title], description: params[:description])
                render json: book, except: :image
            end
            
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
    render json: @books
  end

  def new
    @book = current_author.books.new
  end

  def create
    @book = current_author.books.new(book_params)

    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @book = current_author.books.find(params[:id])
  end

  def edit
    @book = current_author.books.find(params[:id])
  end

  def update
    @book = current_author.books.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end
  def assigntags
    tag = Tag.find(params['tag'][:id])
    book = Book.find_by_id(params['book'][:id])
    Bookstag.find_or_create_by(book_id: book.id, tag_id: tag.id)
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :description)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @book.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Books App", books_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <%= link_to "Add Book", new_book_path, class: "nav-link" %>
          <!-- <a class="nav-link" href="#">Add Book <span class="sr-only">(current)</span></a> -->
        </li>
        <li class="nav-item">
         <%= link_to "All Books", books_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "Logout", author_session_path, method: :delete, class: "nav-link" %>
        </li>
        
        <li class="nav-item">
         <%= link_to "Settings", edit_author_password_path, class: "nav-link" %>
        </li>
        
      </ul>
    </div>
  </nav>

app/views/books/assigntag.html.erb
<h1>New tags</h1>
<div class="my-4">
  <%=  form_tag(assign_tags_path, method: :post) do %>
    <%= collection_select :book, :id, current_author.books.all.order('title ASC'), :id, :title,{include_blank: 'Select Book'} %>
    <%= collection_select :tag, :id, Tag.all.order('name ASC'), :id, :name,{include_blank: 'Select Tag'} %>
    <%= submit_tag 'Assign Tag' , class: "btn btn-dark select" %>
  <% end %>
  
</div>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render "form" %>

app/views/books/index.html.erb
<%= link_to "Create New Tags", new_tag_path, class: "btn btn-dark my-2 mx-2" %>
<%= link_to "Assign Tags to books", books_assigntag_path, class: "btn btn-dark my-2" %>

<table class="table">
    <thead>
      <tr>
        <th scope="col">Books</th>
        <th scope="col">Tags</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @books.each_wit_index do |book| %>
        <td><%= index + 1%></td>
        <td><%= book.title%></td>
        <td>
          <% book.tags.each do |tag| %>
          <button class="btn-primary"><%=tag.name%></button>
          <% end %>
        </td>
        
        <td><%= link_to "Show", book_path(book) %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td> 
            <%= link_to "Destroy", book_path(book), data: {
                turbo_method: :delete,
                turbo_confirm: "1 bar phr soch lo?"
              } %>
        </td>
      </tr>
      <% end %>

    </tbody>
  </table>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render "form" %>

app/views/books/show.html.erb
<h1 class="mx-4"><%= @book.title %></h1>

<p class="mx-4"><%= @book.description %></p>

<%= link_to "Edit", edit_book_path(@book), class: "btn btn-primary my-1 mx-4" %>
<%= link_to "Go Back", books_path, class:"btn btn-primary" %>